# Generated by Django 4.2.1 on 2023-05-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="show",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
