# Generated by Django 4.2.1 on 2023-05-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theater", "0002_show_end_date_show_start_date_alter_show_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fare",
            name="show",
        ),
        migrations.AddField(
            model_name="fare",
            name="screen_show",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fare",
                to="theater.screenshowmapper",
            ),
            preserve_default=False,
        ),
    ]
