# Generated by Django 4.2.1 on 2023-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theater", "0003_remove_fare_show_fare_screen_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="seat_number",
        ),
        migrations.AddField(
            model_name="seat",
            name="column",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="row",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
