# Generated by Django 4.2.1 on 2023-05-09 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theater", "0004_remove_seat_seat_number_seat_column_seat_row"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingseat",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="bookingseat",
            name="seat",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="BookingSeat",
        ),
    ]
