# Generated by Django 4.2.1 on 2023-05-09 21:54

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_status",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="booking_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingseat",
            name="booking_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
