# Generated by Django 4.2.1 on 2023-05-09 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_remove_booking_booking_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingseat",
            name="total_amount",
        ),
    ]
