# Generated by Django 4.2.1 on 2023-05-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_bookingseat_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="booking.booking",
            ),
        ),
    ]
