# Generated by Django 4.2.1 on 2023-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_payment_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("DEBIT CARD", "Debit card"),
                    ("CREDIT CARD", "Credit card"),
                    ("NET BANKING", "Net banking"),
                    ("UPI", "UPI"),
                ],
                max_length=20,
            ),
        ),
    ]
